server:
  port: 8080

spring:
  redis:
    jedis:
      pool:
        max-active: 100  #最大连接数
        max-idle: 8 #最大空闲数
        min-idle: 2 #最小空闲数
    host: 192.168.131.130
    port: 6379
    password: xindekaishi
    timeout: 20000
